### ISSUE TITLE
Create Feature schema and GFF3 loading

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-plugin-apollo#59]
- Update the schema in `packages/apollo-schemas/src/feature.schema.ts` to the current schema.
- Create a Feature module that has one endpoint, `features/importGFF3`
  - This will take the GFF3 text as a file upload in the body of a POST request
  - The assembly will also be specified in the POST request
  - e.g. the request might look like this: `curl http://localhost:3999/features/importGFF3 -F 'file=@./volvox.gff3' -F 'assembly=assemblyId'
- Make sure refSeq ID is validated with `mongoose-id-validator`, and that the right combination of assembly and refSeq are chosen

**Comment by kyostiebi** [comment]
How about refSeqId for the commented lines that appears in the beginning of GFF3 file? I mean these
# Note: See http://song.sourceforge.net
# multi-exon gene - several linked CDSs
# single exon gene - one CDS only
##gff-version 3

Should we just get any existing refSeqId (in given assembly) for those? We cannot leave refSeqId empty because we have FK constraint.

**Comment by garrettjstevens** [comment]
Let's ignore comments, directives, and sequences for now. Don't load those, just the features.

**Comment by kyostiebi** [comment]
Implemented in branch Issue59
